version: "3"

services:
  db:
    image: postgres
    networks: 
      - bridge
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
  dj:
    container_name: dj
    networks: 
      - bridge
    environment:
        DJ_SECRET: ${DJ_SECRET}
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
    build: django
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./django:/code
    ports:
      - 80:80
    depends_on:
      - db

  ng:
    container_name: ng
    build: angular
    networks:
      - bridge
    ports:
      - 8080:80

networks:
  bridge:
    driver: bridge
