version: "3"

services:
  db:
    image: postgres
    networks: 
      - bridge
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
  dj:
    container_name: dj
    networks: 
      - bridge
    environment:
      - DJANGO_SETTINGS=dev
    build:
      context: .
      dockerfile: ./django/Dockerfile
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./django:/code
    ports:
      - 80:80
    depends_on:
      - db

  ng:
    container_name: ng
    build: 
      context: .
      dockerfile: ./angular/Dockerfile
    networks:
      - bridge
    ports:
      - 8080:80

networks:
  bridge:
    driver: bridge
