version: "3"

services:
  db:
    image: postgres
    networks: 
      - bridge
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
  dj:
    container_name: dj
    networks: 
      - bridge
#    environment:
#      - DJANGO_SETTINGS=dev
    build:
      context: .
      dockerfile: ./django/Dockerfile
    restart: always
#    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./django:/code
      - uwsgi-socket:/tmp/
#    ports:
#      - 8080:8080
    depends_on:
      - db

  ng:
    container_name: ng
    build: 
      context: .
      dockerfile: ./angular/Dockerfile
    restart: always
    networks:
      - bridge
    ports:
      - 80:80
      - 443:443
    volumes:
      - uwsgi-socket:/tmp

networks:
  bridge:
    driver: bridge

volumes:
  uwsgi-socket:
